version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: buckshot_nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - buckshot-app
      - frontend

  buckshot-app:
    image: wing2k4/buckshot-backend:v1.0.0
#    build: .
    container_name: buckshot_server
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - LOGGING_LEVEL_ORG_EXAMPLE_BUCKSHOT_ROULETTE=DEBUG
      - SPRING_DEVTOOLS_RESTART_ENABLED=false
      - SERVER_SERVLET_SESSION_TIMEOUT=30m

  frontend:
    image: wing2k4/buckshot-frontend:v1.0.0
#    build: ./frontend
    container_name: buckshot_frontend
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - buckshot-app
