name: Build & Push Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/workflows/backend.yml'

jobs:
  build-backend:
    name: Build Backend (Java)
    runs-on: ubuntu-latest
    environment: Docker hub

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          #Tên image
          tags: wing2k4/buckshot-backend:v1.0.0,
            wing2k4/buckshot-backend:latest

  deploy-azure:
    needs: build-backend
    runs-on: ubuntu-latest
    environment: Docker hub

    steps:
      - name: Deploy to Azure Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Dừng và xóa container cũ
            docker stop game-container || true
            docker rm game-container || true

            # Xóa images cũ
            docker rmi ${{ secrets.DOCKER_USERNAME }}/buckshot-backend:latest || true
            
            # Tải images mới
            docker pull ${{ secrets.DOCKER_USERNAME }}/buckshot-backend:v1.0.0
            # Chạy game
            docker run -d \
              --name gameserver-container \
              --restart always \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/buckshot-frontend:v1.0.0