name: Build & Push Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    environment: Docker hub
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      #Chẩn bị testing environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint Check (Kiểm tra cú pháp code)
        run: npm run lint


      # Nếu có test unit
      # - name: Run Unit Tests
      #   run: npm test

      - name: Try Build (Build thử xem có lỗi TypeScript không)
        run: npm run build

      # ---ĐÓNG GÓI DOCKER ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/buckshot-frontend:v1.0.0
            ${{ secrets.DOCKERHUB_USERNAME }}/buckshot-frontend:latest

  deploy-azure:
    needs: build-frontend
    runs-on: ubuntu-latest
    environment: Docker hub

    steps:
      - name: Deploy to Azure Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          envs: DOCKER_USERNAME,DOCKERHUB_TOKEN
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          script: |
            # Đăng nhập Docker Hub
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
            
            # Dừng và xóa container cũ
            docker stop game-container || true
            docker rm game-container || true

            # Xóa images cũ
            docker rmi $DOCKER_USERNAME/buckshot-frontend:v1.0.0 || true

            # Tải images mới
            docker pull $DOCKER_USERNAME/buckshot-frontend:v1.0.0

            # Chạy game
            docker run -d \
              --name game-container \
              --restart always \
              -p 3000:3000 \
              $DOCKER_USERNAME/buckshot-frontend:v1.0.0
            
            # Đăng xuất Docker Hub (tùy chọn, để an toàn)
            docker logout
