name: Java CI with Maven & Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    environment: Docker hub

    steps:
    # --- PHẦN 1: Dùng java để build và test ---
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build & Test with Maven
      run: mvn -B package --file pom.xml
      # Lưu ý: Bước này chạy test. Nếu test fail, quy trình dừng ngay tại đây.

    # --- PHẦN 2: THÊM VÀO (Để đóng gói Docker) ---
    
    # Đăng nhập vào Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build Docker Image và đẩy lên
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: wing2k4/buckshot_roulette_game:lastest
